/**
 * What a download promises, tested apart from how it is delivered.
 *
 * `docs/PLAN.md` §7.5 sets three constraints on an export, and each is a claim
 * a reader could check by opening the file: the numbers are the artefact's and
 * not the drawing's, the file says where it came from, and an image states its
 * filters inside the image. Those are the cases below.
 *
 * The DOM half — rasterising and saving — is not tested here and holds no
 * decisions; it is the mechanical layer under everything above.
 */

import { describe, expect, it } from 'vitest';
import {
	captionSvg,
	csvField,
	csvHeader,
	escapeXml,
	filename,
	nest,
	provenanceLines,
	provenanceOf,
	toCsv
} from './export';
import type { ExportRequest, Provenance } from './export';
import type { BaseMeta } from './types';

const meta = {
	script: '04_series.py',
	generated: '2026-08-09T09:17:18Z',
	analysis_hash: '1234analysis',
	lexicon_version: 2,
	git_commit: 'bec9e1a72a95d7ed557fb3e5059625b8680b967a',
	inputs: [{ path: 'data/derived/speeches_flagged.parquet', bytes: 1, sha256: 'abc123' }],
	configs: [{ path: 'config/lexicon.yml', bytes: 1, sha256: 'def456' }]
} as unknown as BaseMeta;

const provenance = (): Provenance => provenanceOf(meta, 'series/annual.json');

const request = (over: Partial<ExportRequest> = {}): ExportRequest => ({
	title: 'Rate over time',
	columns: ['year', 'rate'],
	rows: [
		[1994, 0.128_571_428_571_43],
		[1995, null]
	],
	provenance: provenance(),
	...over
});

describe('reading a manifest', () => {
	it('carries the identifiers the methods page shows', () => {
		const read = provenance();
		expect(read.script).toBe('04_series.py');
		expect(read.lexiconVersion).toBe(2);
		expect(read.analysisHash).toBe('1234analysis');
		expect(read.gitCommit).toBe('bec9e1a72a95d7ed557fb3e5059625b8680b967a');
		expect(read.inputs).toEqual([
			{ path: 'data/derived/speeches_flagged.parquet', sha256: 'abc123' }
		]);
	});

	it('omits what it does not have rather than printing undefined', () => {
		const thin = provenanceOf({ script: '05_lexical.py' } as unknown as BaseMeta, 'lexical/x.json');
		expect(thin.lexiconVersion).toBeNull();
		expect(thin.analysisHash).toBeNull();
		expect(thin.gitCommit).toBeNull();
		expect(thin.inputs).toEqual([]);
		expect(provenanceLines(thin).join('\n')).not.toMatch(/undefined|null/);
	});

	it('drops manifest entries that are not a path and a hash', () => {
		const ragged = provenanceOf(
			{
				script: 'x.py',
				inputs: ['nope', { path: 'a' }, { path: 'b', sha256: 'h' }]
			} as unknown as BaseMeta,
			'a.json'
		);
		expect(ragged.inputs).toEqual([{ path: 'b', sha256: 'h' }]);
	});
});

describe('the CSV header', () => {
	it('names the artefact, the script, the analytical hash, the lexicon and the commit', () => {
		const header = csvHeader(request()).join('\n');
		expect(header).toContain('# artifact: series/annual.json');
		expect(header).toContain('# generated by: 04_series.py on 2026-08-09T09:17:18Z');
		expect(header).toContain('# lexicon version: 2');
		expect(header).toContain('# analysis hash: 1234analysis');
		expect(header).toContain('bec9e1a72a95d7ed557fb3e5059625b8680b967a');
		expect(header).toContain('sha256:abc123');
	});

	it('is entirely comment rows, so a reader can skip it mechanically', () => {
		expect(csvHeader(request()).every((line) => line.startsWith('# '))).toBe(true);
	});

	it('records what was on screen without implying the file is limited to it', () => {
		const header = csvHeader(request({ filters: ['term: genocide', 'window: ±5'] })).join('\n');
		expect(header).toContain('# on screen: term: genocide; window: ±5');
		// The point of §7.5's first constraint: the file is wider than the figure.
		expect(header).toMatch(/# rows: .*including any the figure was not showing/);
	});

	it('lets a caller correct the scope line when the file really is a subset', () => {
		const header = csvHeader(request({ scope: 'the filtered rows only' })).join('\n');
		expect(header).toContain('# rows: the filtered rows only');
	});
});

describe('CSV fields', () => {
	it('leaves a plain number unquoted so it arrives as a number', () => {
		expect(csvField(1994)).toBe('1994');
		expect(csvField(0.5)).toBe('0.5');
	});

	it('quotes only for the delimiter, a quote, a newline or edge space', () => {
		expect(csvField('Serbia')).toBe('Serbia');
		expect(csvField('Serbia, and Montenegro')).toBe('"Serbia, and Montenegro"');
		expect(csvField('he said "genocide"')).toBe('"he said ""genocide"""');
		expect(csvField('two\nlines')).toBe('"two\nlines"');
		expect(csvField(' padded ')).toBe('" padded "');
	});

	it('writes an absent value as an empty field, not as the word null', () => {
		expect(csvField(null)).toBe('');
		expect(csvField(undefined)).toBe('');
	});
});

describe('the CSV body', () => {
	it('keeps full precision rather than the figure’s rounding', () => {
		expect(toCsv(request())).toContain('1994,0.12857142857143');
	});

	it('puts the column row directly after the comments', () => {
		const lines = toCsv(request()).split('\r\n');
		const first = lines.findIndex((line) => !line.startsWith('#'));
		expect(lines[first]).toBe('year,rate');
	});

	it('ends with a newline so the last row is a complete record', () => {
		expect(toCsv(request()).endsWith('\r\n')).toBe(true);
	});

	it('writes a withheld rate as blank, matching the artefact’s null', () => {
		expect(toCsv(request())).toContain('1995,\r\n');
	});
});

describe('filenames', () => {
	it('slugs the parts it is given', () => {
		expect(filename(['unsc', 'genocide', 'Rate over time'], 'csv')).toBe(
			'unsc-genocide-rate-over-time.csv'
		);
	});

	it('drops empty parts rather than leaving a double dash', () => {
		expect(filename(['unsc', '', null, undefined, 'x'], 'csv')).toBe('unsc-x.csv');
	});

	it('removes what a download folder would mangle', () => {
		expect(filename(['a/b', 'c,d', '±5'], 'png')).toBe('a-b-c-d-5.png');
	});

	it('never produces a bare extension', () => {
		expect(filename([], 'csv')).toBe('export.csv');
	});
});

describe('captioning an image', () => {
	const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="600" height="300"><g/></svg>';
	const colours = { ink: '#14171a', faint: '#626a74', paper: '#f1f2ee', rule: '#d6d9cf' };

	const caption = (filters?: string[]) =>
		captionSvg({
			svg,
			width: 600,
			height: 300,
			title: 'Rate over time',
			filters,
			provenance: provenance(),
			colours
		});

	it('states the filters inside the image, not only in the filename', () => {
		const out = caption(['term: genocide', 'period: 1992-2023']);
		expect(out).toContain('term: genocide');
		expect(out).toContain('period: 1992-2023');
	});

	it('carries the same provenance the CSV does', () => {
		const out = caption();
		for (const line of provenanceLines(provenance())) expect(out).toContain(line);
	});

	it('grows the canvas for the caption instead of covering the chart', () => {
		const out = caption(['term: genocide']);
		const height = Number(/^<svg[^>]*\sheight="(\d+(?:\.\d+)?)"/.exec(out)?.[1]);
		expect(height).toBeGreaterThan(300);
		// The chart keeps its own box, unscaled and uncropped.
		expect(out).toContain('<svg x="0" y="0" width="600" height="300"');
	});

	it('writes literal colours, because the file is read without the page CSS', () => {
		const out = caption();
		expect(out).toContain('#f1f2ee');
		expect(out).not.toContain('var(--');
	});

	it('is a standalone document with its own namespace', () => {
		expect(caption().startsWith('<svg xmlns="http://www.w3.org/2000/svg"')).toBe(true);
	});

	it('escapes a title that would otherwise break the markup', () => {
		const out = captionSvg({
			svg,
			width: 600,
			height: 300,
			title: 'Rate of "genocide" & <related>',
			provenance: provenance(),
			colours
		});
		expect(out).toContain('Rate of &quot;genocide&quot; &amp; &lt;related&gt;');
		expect(out).not.toContain('& <related>');
	});
});

describe('nesting the chart', () => {
	const echarts =
		'<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="1037" height="420"><g/></svg>';

	it('never leaves a duplicated sizing attribute', () => {
		// The bug this exists for: prepending width/height to a root that already
		// had them makes the file a fatal XML parse error, which browsers forgive
		// inline and `new Image()` does not. It rendered on screen and refused to
		// rasterise, with no message.
		const open = /^<svg\b[^>]*>/.exec(nest(echarts, 908, 420))![0];
		for (const attribute of ['width', 'height', 'x', 'y']) {
			const found = open.match(new RegExp(`\\s${attribute}\\s*=`, 'g')) ?? [];
			expect(found.length, `${attribute} appears ${found.length} times`).toBe(1);
		}
	});

	it('takes the box it is given', () => {
		const open = /^<svg\b[^>]*>/.exec(nest(echarts, 908, 400))![0];
		expect(open).toContain('width="908"');
		expect(open).toContain('height="400"');
	});

	it('adds a viewBox from the size it removes, so the chart scales not crops', () => {
		expect(nest(echarts, 908, 400)).toContain('viewBox="0 0 1037 420"');
	});

	it('leaves an existing viewBox alone', () => {
		const withBox =
			'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 20" width="10"><g/></svg>';
		const out = nest(withBox, 100, 200);
		expect(out).toContain('viewBox="0 0 10 20"');
		expect((out.match(/viewBox/g) ?? []).length).toBe(1);
	});

	it('keeps the namespace and the body untouched', () => {
		const out = nest(echarts, 908, 420);
		expect(out).toContain('xmlns="http://www.w3.org/2000/svg"');
		expect(out).toContain('<g/></svg>');
	});

	it('leaves markup it cannot parse as it found it', () => {
		expect(nest('not svg at all', 10, 10)).toBe('not svg at all');
	});
});

describe('XML escaping', () => {
	it('covers every character that could close a tag or an attribute', () => {
		expect(escapeXml(`&<>"'`)).toBe('&amp;&lt;&gt;&quot;&apos;');
	});
});
