/**
 * Taking a figure away with you.
 *
 * `docs/PLAN.md` §7.5 asks that every chart and generated table be downloadable
 * from beside the thing itself, and sets three constraints that are really one
 * constraint: a downloaded file must not become a second source of truth.
 *
 * **The numbers come from the artefact, not from the drawing.** A caller passes
 * the rows the artefact holds, at full precision, including rows a top-N cut or
 * a zoom is currently hiding. Nothing here reads a chart's state, so nothing
 * here can export "whatever happened to be visible" — which is a screenshot
 * with commas in it. What was on screen is recorded as a *filter line* instead,
 * and the header says in words that the file is wider than the figure was.
 *
 * **The file carries its own provenance.** Every export leads with comment rows
 * naming the artefact, the script that wrote it, the lexicon version, the
 * pipeline commit and the input hashes — the identifiers the methods page
 * shows. A downloaded table with no version is an orphan the moment a figure is
 * regenerated, and this project regenerates figures.
 *
 * **An image states its filters in the image.** Not in the filename, which
 * survives one rename. `captionSvg` draws the title, the filters and the
 * provenance into the picture itself, so a chart pasted into a slide still says
 * what it is.
 *
 * Everything above is pure string work and is tested. The two functions that
 * touch the DOM — rasterising and saving — are the thin mechanical layer at the
 * bottom, and hold no decisions.
 */

import type { Meta } from './types';

/** Where a number came from, as the artefact's own manifest records it. */
export interface Provenance {
	/** Path under `static/data/`, e.g. `series/annual.json`. */
	artifact: string;
	script: string;
	generated: string;
	gitCommit: string | null;
	lexiconVersion: number | null;
	inputs: { path: string; sha256: string }[];
	configs: { path: string; sha256: string }[];
}

interface Described {
	path?: unknown;
	sha256?: unknown;
}

const described = (value: unknown): { path: string; sha256: string }[] =>
	Array.isArray(value)
		? value
				.filter((item): item is Described => typeof item === 'object' && item !== null)
				.filter((item) => typeof item.path === 'string' && typeof item.sha256 === 'string')
				.map((item) => ({ path: String(item.path), sha256: String(item.sha256) }))
		: [];

/**
 * Read a payload's `meta` block into the fields an export header needs.
 *
 * Deliberately total: `meta` is typed loosely because the Python side owns it,
 * so anything missing becomes null and is omitted from the header rather than
 * printed as "undefined". A header that lies about provenance is worse than a
 * header that is short.
 */
export function provenanceOf(meta: Meta, artifact: string): Provenance {
	return {
		artifact,
		script: typeof meta.script === 'string' ? meta.script : 'unknown',
		generated: typeof meta.generated === 'string' ? meta.generated : 'unknown',
		gitCommit: typeof meta.git_commit === 'string' ? meta.git_commit : null,
		lexiconVersion: Number.isFinite(meta.lexicon_version) ? Number(meta.lexicon_version) : null,
		inputs: described(meta.inputs),
		configs: described(meta.configs)
	};
}

export interface ExportRequest {
	/** The figure's title, as the page shows it. */
	title: string;
	columns: string[];
	/** Full precision. Numbers are not formatted; null becomes an empty field. */
	rows: (string | number | boolean | null | undefined)[][];
	provenance: Provenance;
	/** What the figure was showing, e.g. `['term: genocide', 'window: ±5']`. */
	filters?: string[];
	/**
	 * How the file's rows relate to the figure's. Defaults to saying the file is
	 * the whole artefact — override only when that is not true.
	 */
	scope?: string;
}

const SITE = 'Genocide at the Security Council';
const REPO = 'https://github.com/fmadore/genocide-at-the-security-council';
const DEFAULT_SCOPE = 'every row the artefact holds, including any the figure was not showing';

/**
 * The provenance block, as lines without their comment marker.
 *
 * Shared by the CSV header and the image caption so the two cannot describe the
 * same download differently.
 */
export function provenanceLines(provenance: Provenance): string[] {
	const lines = [
		`artifact: ${provenance.artifact}`,
		`generated by: ${provenance.script} on ${provenance.generated}`
	];
	if (provenance.lexiconVersion !== null) {
		lines.push(`lexicon version: ${provenance.lexiconVersion}`);
	}
	if (provenance.gitCommit) lines.push(`pipeline commit: ${provenance.gitCommit}`);
	for (const input of provenance.inputs) lines.push(`input: ${input.path} sha256:${input.sha256}`);
	for (const config of provenance.configs) {
		lines.push(`config: ${config.path} sha256:${config.sha256}`);
	}
	return lines;
}

/** The comment rows a CSV leads with. `#` is what pandas and R read as a comment. */
export function csvHeader(request: ExportRequest): string[] {
	const lines = [SITE, `figure: ${request.title}`, ...provenanceLines(request.provenance)];
	if (request.filters?.length) lines.push(`on screen: ${request.filters.join('; ')}`);
	lines.push(`rows: ${request.scope ?? DEFAULT_SCOPE}`);
	lines.push(`licence: CC BY 4.0 — ${REPO}`);
	return lines.map((line) => `# ${line}`);
}

/**
 * Quote a field only where the format requires it.
 *
 * Blanket quoting is what the concordance did, and it makes every numeric
 * column arrive in a spreadsheet as text. Quote for the delimiter, the quote
 * character, a newline, or surrounding space that a reader would otherwise lose.
 */
export function csvField(value: string | number | boolean | null | undefined): string {
	if (value === null || value === undefined) return '';
	const text = String(value);
	return /[",\n\r]|^\s|\s$/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
}

/** The whole file: provenance comments, the header row, then the rows. */
export function toCsv(request: ExportRequest): string {
	const body = request.rows.map((row) => row.map(csvField).join(','));
	return [...csvHeader(request), request.columns.map(csvField).join(','), ...body, ''].join('\r\n');
}

/**
 * A filename that says what it holds and sorts sensibly beside its siblings.
 *
 * Slugged rather than quoted: these land in download folders shared with every
 * other file a reader has, and a name with a comma or a slash in it is a name
 * some tool will mangle.
 */
export function filename(parts: (string | number | null | undefined)[], extension: string): string {
	const slug = parts
		.filter((part) => part !== null && part !== undefined && String(part).trim() !== '')
		.map((part) =>
			String(part)
				.toLowerCase()
				.replace(/[^a-z0-9]+/g, '-')
				.replace(/^-+|-+$/g, '')
		)
		.filter(Boolean)
		.join('-');
	return `${slug || 'export'}.${extension.replace(/^\./, '')}`;
}

const XML_ESCAPES: Record<string, string> = {
	'&': '&amp;',
	'<': '&lt;',
	'>': '&gt;',
	'"': '&quot;',
	"'": '&apos;'
};

/**
 * The XML twin of `escapeHtml` in `format.ts`, and deliberately not the same
 * function: an apostrophe becomes `&apos;` here and `&#39;` there. `&apos;` is
 * XML, not HTML 4, so the numeric form is the one a tooltip needs and the named
 * form is the one belonging in a downloaded `.svg`. Two escapers, one sentence
 * apart, rather than one that is subtly wrong in whichever place it is not.
 */
export const escapeXml = (value: string): string =>
	value.replace(/[&<>"']/g, (character) => XML_ESCAPES[character]);

export interface CaptionRequest {
	/** The chart's serialised `<svg>` markup. */
	svg: string;
	width: number;
	height: number;
	title: string;
	filters?: string[];
	provenance: Provenance;
	/** Resolved colours — the exported file has none of the page's CSS. */
	colours: { ink: string; faint: string; paper: string; rule: string };
	fontFamily?: string;
}

/** Caption geometry, in px. Small type: this is apparatus, not the figure. */
const CAPTION = { pad: 16, titleSize: 15, lineSize: 10.5, lineGap: 13.5, rule: 1 };

/**
 * Wrap a chart's SVG in a captioned frame.
 *
 * The chart is nested unchanged as an inner `<svg>` rather than reparented, so
 * nothing about its own coordinate system has to be understood or preserved by
 * hand. Everything added sits below it.
 *
 * Colours are passed in and written as literals because a downloaded file is
 * read with none of this site's CSS: `var(--ink)` in an exported SVG renders as
 * black on black in a dark viewer, or as nothing at all.
 */
/** Sizing attributes on the chart's own root, which have to go before ours can land. */
const SIZING = /\s(?:x|y|width|height)\s*=\s*("[^"]*"|'[^']*'|[^\s>]+)/g;

/**
 * Place a chart's `<svg>` inside the caption frame as a nested element.
 *
 * The subtlety that cost a debugging pass: ECharts already writes `width` and
 * `height` on its root, so *prepending* ours produced a tag carrying each twice.
 * Duplicate attributes are a fatal XML parse error, and while browsers forgive
 * that in inline HTML, an SVG loaded through `new Image()` is parsed strictly —
 * so the file looked fine on screen and failed to rasterise, with `onerror` and
 * no message. The old sizes are stripped before the new ones are written.
 *
 * A root with no `viewBox` is given one from the size it is losing. Without it,
 * replacing `width` would crop the chart rather than scale it, because width and
 * height on an outermost-turned-nested `<svg>` size the viewport, not the
 * content.
 */
export function nest(svg: string, width: number, height: number): string {
	const open = /^<svg\b[^>]*>/.exec(svg)?.[0];
	if (!open) return svg;
	const ownWidth = Number(/\swidth\s*=\s*["']?([\d.]+)/.exec(open)?.[1]);
	const ownHeight = Number(/\sheight\s*=\s*["']?([\d.]+)/.exec(open)?.[1]);
	let tag = open.replace(SIZING, '');
	if (!/\sviewBox\s*=/.test(tag) && ownWidth > 0 && ownHeight > 0) {
		tag = tag.replace(/^<svg\b/, `<svg viewBox="0 0 ${ownWidth} ${ownHeight}"`);
	}
	tag = tag.replace(/^<svg\b/, `<svg x="0" y="0" width="${width}" height="${height}"`);
	return tag + svg.slice(open.length);
}

export function captionSvg(request: CaptionRequest): string {
	const { svg, width, height, title, provenance, colours } = request;
	const font = request.fontFamily ?? 'Archivo, system-ui, sans-serif';
	const lines = [
		...(request.filters?.length ? [request.filters.join('  ·  ')] : []),
		...provenanceLines(provenance)
	];
	const captionHeight =
		CAPTION.pad * 2 + CAPTION.titleSize + CAPTION.lineGap * lines.length + CAPTION.rule;
	const total = height + captionHeight;

	const inner = nest(svg, width, height);

	let cursor = height + CAPTION.pad + CAPTION.titleSize;
	const text = [
		`<text x="${CAPTION.pad}" y="${cursor}" font-family="${escapeXml(font)}" ` +
			`font-size="${CAPTION.titleSize}" font-weight="600" fill="${escapeXml(colours.ink)}">` +
			`${escapeXml(title)}</text>`
	];
	for (const line of lines) {
		cursor += CAPTION.lineGap;
		text.push(
			`<text x="${CAPTION.pad}" y="${cursor}" font-family="${escapeXml(font)}" ` +
				`font-size="${CAPTION.lineSize}" fill="${escapeXml(colours.faint)}">` +
				`${escapeXml(line)}</text>`
		);
	}

	return [
		`<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" ` +
			`width="${width}" height="${total}" viewBox="0 0 ${width} ${total}">`,
		`<rect width="${width}" height="${total}" fill="${escapeXml(colours.paper)}"/>`,
		inner,
		`<line x1="0" y1="${height}" x2="${width}" y2="${height}" ` +
			`stroke="${escapeXml(colours.rule)}" stroke-width="${CAPTION.rule}"/>`,
		...text,
		'</svg>'
	].join('\n');
}

/* --- The DOM layer. No decisions below this line. ------------------------- */

/** Rasterise captioned SVG markup. `scale` of 2 gives a usable print density. */
export async function svgToPng(svg: string, width: number, height: number, scale = 2) {
	const blob = new Blob([svg], { type: 'image/svg+xml;charset=utf-8' });
	const url = URL.createObjectURL(blob);
	try {
		const image = new Image();
		image.width = width;
		image.height = height;
		await new Promise<void>((resolve, reject) => {
			image.onload = () => resolve();
			image.onerror = () => reject(new Error('The figure could not be rasterised.'));
			image.src = url;
		});
		const canvas = document.createElement('canvas');
		canvas.width = Math.round(width * scale);
		canvas.height = Math.round(height * scale);
		const context = canvas.getContext('2d');
		if (!context) throw new Error('This browser gave no 2D canvas context.');
		context.scale(scale, scale);
		context.drawImage(image, 0, 0, width, height);
		return await new Promise<Blob>((resolve, reject) => {
			canvas.toBlob(
				(result) => (result ? resolve(result) : reject(new Error('The PNG was empty.'))),
				'image/png'
			);
		});
	} finally {
		URL.revokeObjectURL(url);
	}
}

/**
 * Save a blob under a name.
 *
 * The anchor is put in the document before it is clicked and the object URL is
 * revoked on the next frame rather than immediately: a detached anchor does not
 * reliably trigger a download outside Chromium, and revoking synchronously can
 * beat the browser to reading the blob.
 */
export function save(blob: Blob, name: string): void {
	const url = URL.createObjectURL(blob);
	const anchor = document.createElement('a');
	anchor.href = url;
	anchor.download = name;
	anchor.style.display = 'none';
	document.body.append(anchor);
	anchor.click();
	anchor.remove();
	setTimeout(() => URL.revokeObjectURL(url), 0);
}

/** Save a built CSV. The BOM is what makes Excel read UTF-8 as UTF-8. */
export function saveCsv(csv: string, name: string): void {
	save(new Blob(['﻿', csv], { type: 'text/csv;charset=utf-8' }), name);
}
