import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { base } from '../../playwright.config';

const concordance = `${base}/concordance/`;

async function expectNoAxeViolations(page: import('@playwright/test').Page) {
	const { violations } = await new AxeBuilder({ page }).analyze();
	expect(violations).toEqual([]);
}

test('a filtered concordance URL restores its analytical state under the base path', async ({
	page
}) => {
	await page.goto(
		`${concordance}?term=genocide&country=Rwanda&type=Mentioned&from=2014&to=2014&month=6&sort=right`
	);

	await expect(page.getByRole('heading', { name: 'Concordance', level: 1 })).toBeVisible();
	await expect(page.getByRole('combobox', { name: 'Speaker', exact: true })).toHaveValue('Rwanda');
	await expect(page.getByRole('combobox', { name: 'Participant type', exact: true })).toHaveValue(
		'Mentioned'
	);
	await expect(page.getByRole('combobox', { name: 'Month', exact: true })).toHaveValue('6');
	await expect(page.getByRole('button', { name: 'Right' })).toHaveAttribute('aria-pressed', 'true');
	await expect(page.locator('.status')).toContainText('2 of 4 lines');
	await expect(page).toHaveURL(/\/genocide-at-the-security-council\/concordance\//);
	await expectNoAxeViolations(page);
});

test('the filtered CSV records filters, provenance, and only matching rows', async ({ page }) => {
	await page.goto(`${concordance}?q=warned`);
	await expect(page.locator('.status')).toContainText('1 of 4 lines');

	const pending = page.waitForEvent('download');
	await page.getByRole('button', { name: 'Export 1 to CSV' }).click();
	const download = await pending;
	const path = await download.path();
	expect(path).not.toBeNull();
	const csv = await readFile(path!, 'utf8');

	expect(download.suggestedFilename()).toBe('unsc-genocide-concordance-filtered.csv');
	expect(csv).toContain('# artifact: kwic/genocide.json');
	expect(csv).toContain('# pipeline commit: fixture');
	expect(csv).toContain('# on screen: search: warned; sorted by: date');
	expect(csv).toContain('SC07000-01-001#1');
	expect(csv).not.toContain('SC07000-01-001#2');
});

test('an exported figure embeds its reading and provenance in the image', async ({ page }) => {
	await page.goto(`${base}/`);
	const figure = page.locator('figure.figure').filter({
		has: page.getByRole('heading', { name: /Occurrences and share of speeches/, level: 2 })
	});
	await expect(figure.locator('.chart svg')).toBeVisible({ timeout: 15_000 });

	const pending = page.waitForEvent('download');
	await figure.getByRole('button', { name: 'SVG', exact: true }).click();
	const download = await pending;
	const path = await download.path();
	expect(path).not.toBeNull();
	const svg = await readFile(path!, 'utf8');

	expect(download.suggestedFilename()).toBe('unsc-occurrences-and-share.svg');
	expect(svg).toContain('Occurrences and share of speeches');
	expect(svg).toContain('drawn: genocide — occurrences and share of speeches');
	expect(svg).toContain('artifact: series/annual.json');
	expect(svg).toContain('generated by: 04_series.py on 2026-08-24T00:00:00Z');
	expect(svg).toContain('pipeline commit: fixture');
});

test('a concordance hit opens, copies, and traverses exact occurrences', async ({
	context,
	page
}) => {
	await context.grantPermissions(['clipboard-read', 'clipboard-write']);
	await page.goto(concordance);
	await page.locator('.line').first().click();
	const evidence = page.getByRole('link', { name: 'Read the whole speech' });
	await expect(evidence).toHaveAttribute(
		'href',
		`${base}/reader/SC07000-01?term=genocide&speech=SC07000-01-001&occurrence=SC07000-01-001%231`
	);
	await evidence.click();

	await expect(
		page.getByRole('heading', { name: 'Protection of civilians', level: 1 })
	).toBeVisible();
	await expect(page.locator('li.target')).toHaveAttribute('id', 'SC07000-01-001');
	await expect(page.locator('li.target mark')).toHaveCount(2);
	await expect(page.locator('mark.occurrence')).toHaveCount(1);
	await expect(page.locator('mark.occurrence')).toHaveText('genocide');
	await expect(page.locator('mark.occurrence')).toHaveAttribute(
		'data-occurrence',
		'SC07000-01-001#1'
	);
	await expect(page.locator('mark.occurrence')).toBeInViewport();
	await page.getByRole('button', { name: 'Copy occurrence link' }).click();
	await expect(page.getByRole('button', { name: 'Occurrence link copied' })).toBeVisible();
	expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(page.url());
	await page.getByRole('button', { name: 'Copy quotation + citation' }).click();
	await expect(page.getByRole('button', { name: 'Quotation copied' })).toBeVisible();
	const quotation = await page.evaluate(() => navigator.clipboard.readText());
	expect(quotation).toContain('“We warned that genocide could occur.”');
	expect(quotation).toContain('Rwanda, UN Security Council, S/PV.7000 (2014-06-11).');
	expect(quotation).toContain('occurrence SC07000-01-001#1.');
	expect(quotation).toContain(page.url());
	await expect(page.getByText('1 of 4', { exact: true })).toBeVisible();
	await page.getByRole('link', { name: 'Next occurrence' }).click();
	await expect(page.locator('mark.occurrence')).toHaveAttribute(
		'data-occurrence',
		'SC07000-01-001#2'
	);
	await expect(page.getByText('2 of 4', { exact: true })).toBeVisible();
	await expect(page.getByRole('link', { name: 'Previous occurrence' })).toBeVisible();

	// The occurrence ID is this project's locator, and it must survive into a
	// reference manager: the official record has no paragraph numbering here.
	const pending = page.waitForEvent('download');
	await page.getByRole('button', { name: 'RIS', exact: true }).click();
	const download = await pending;
	const ris = await readFile((await download.path())!, 'utf8');
	expect(download.suggestedFilename()).toContain('unsc-citation');
	expect(ris).toContain('TY  - GOVDOC');
	// The reader has the meeting loaded, so the citation names the person as
	// well as the delegation — which the concordance alone could not do.
	expect(ris).toContain('AU  - Ms. Example (Rwanda)');
	expect(ris).toContain('M1  - S/PV.7000');
	expect(ris).toContain('SC07000-01-001#2');
	expect(ris.trimEnd().endsWith('ER  -')).toBe(true);

	await expectNoAxeViolations(page);
});

/**
 * The panel's promise is that a count is a count a click delivers, and that the
 * row which applied a filter is the row that releases it. Both are asserted
 * against the URL rather than against the panel's own numbers, because the URL
 * is what a reader copies and what the next visit restores.
 */
test('the result profile narrows and releases the set it counts', async ({ page }) => {
	await page.goto(concordance);
	const profile = page.locator('details.profile');
	await expect(profile).toBeVisible();
	await expect(profile).toContainText('not evidence of emphasis');

	// A row name is clipped to its column and the bar behind the count carries a
	// share with no figure beside it, so the hover has to give back both.
	await expect(
		profile.getByRole('button', {
			name: 'Filter to The situation in Bosnia and Herzegovina, 2 lines'
		})
	).toHaveAttribute('title', 'The situation in Bosnia and Herzegovina — 2 of 4 lines on screen');

	// A year column says which year it is even when it is empty. The title sits
	// on the column rather than the button, because a disabled button swallows
	// the tooltip along with the pointer events.
	const column = (name: string) =>
		profile.locator('.strip li').filter({ has: page.getByRole('button', { name }) });
	await expect(column('Narrow to 2015, 2 lines')).toHaveAttribute('title', '2015: 2 lines');
	await expect(column('1992, no lines')).toHaveAttribute('title', '1992: no lines');

	// A facet row states its count; applying it must produce exactly that many.
	const france = profile.getByRole('button', { name: 'Filter to France, 2 lines' });
	await france.click();
	await expect(page).toHaveURL(/country=France/);
	await expect(page.locator('.status')).toContainText('2 of 4 lines');
	await expect(page.getByRole('combobox', { name: 'Speaker', exact: true })).toHaveValue('France');

	// The same row releases it, and the parameter leaves the URL entirely.
	await profile.getByRole('button', { name: 'Release France, 2 lines' }).click();
	await expect(page).not.toHaveURL(/country=/);
	await expect(page.locator('.status')).toContainText('4 of 4 lines');

	// A year narrows to itself, then releases to the documented corpus range
	// rather than to whatever range preceded it.
	await profile.getByRole('button', { name: 'Narrow to 2015, 2 lines' }).click();
	await expect(page).toHaveURL(/from=2015&to=2015/);
	await expect(page.locator('.status')).toContainText('2 of 4 lines');
	await profile.getByRole('button', { name: 'Release 2015, 2 lines' }).click();
	await expect(page).not.toHaveURL(/from=/);
	await expect(page.locator('.status')).toContainText('4 of 4 lines');

	// The way out to the chronology carries the term and admits what it drops.
	const escape = profile.getByRole('link', { name: /Open the chronology of/ });
	await expect(escape).toHaveAttribute('href', `${base}/chronology?series=genocide`);
	await expect(profile).toContainText('filters here left behind');

	await expectNoAxeViolations(page);
});

test('data failure has an intelligible retry path', async ({ page }) => {
	await page.goto(`${concordance}?term=temporarily-unavailable`);
	await expect(page.locator('.status .error')).toContainText(
		'No data file at kwic/temporarily-unavailable.json (404)'
	);

	const body = await readFile(
		new URL('../fixtures/data/kwic/genocide.json', import.meta.url),
		'utf8'
	);
	await page.route('**/data/kwic/temporarily-unavailable.json', (route) =>
		route.fulfill({ status: 200, contentType: 'application/json', body })
	);
	await page.getByRole('button', { name: 'Try again' }).click();
	await expect(page.locator('.status')).toContainText('4 of 4 lines');
});

test('essential concordance controls remain visible at narrow and wide widths', async ({
	page
}) => {
	for (const viewport of [
		{ width: 390, height: 844 },
		{ width: 1440, height: 900 }
	]) {
		await page.setViewportSize(viewport);
		await page.goto(concordance);
		await expect(page.getByRole('combobox', { name: 'Term', exact: true })).toBeVisible();
		await expect(page.getByRole('searchbox', { name: 'Search', exact: true })).toBeVisible();
		await expect(page.locator('.line').first()).toBeVisible();
	}
});

test('keyboard users retain the actor table and evidence link when the map fails', async ({
	page
}) => {
	await page.route('https://basemaps.cartocdn.com/**', (route) => route.abort('failed'));
	await page.goto(`${base}/actors/?order=token_rate&view=choropleth`); // an old link: `view` is ignored

	await expect(page.getByRole('heading', { name: 'Who said it', level: 1 })).toBeVisible();
	await expect(page.getByRole('combobox', { name: 'Ranked by' })).toHaveValue('token_rate');
	await expect(page).toHaveURL(/\/actors\/?\?order=token_rate$/);
	await expect(page.getByRole('status')).toContainText(
		'Every speaker it would show is in the table',
		{ timeout: 8_000 }
	);
	const table = page.locator('section.table-wrap');
	const rwanda = table.getByRole('button', { name: 'Rwanda' });
	await rwanda.focus();
	await page.keyboard.press('Enter');

	const picked = page.locator('aside.picked');
	await expect(picked.getByRole('heading', { name: 'Rwanda' })).toBeVisible();
	await expect(picked.getByRole('link', { name: 'Read the occurrences' })).toHaveAttribute(
		'href',
		`${base}/concordance?term=genocide&country=Rwanda&from=1992&to=2023`
	);
	await expectNoAxeViolations(page);
});
