import AxeBuilder from '@axe-core/playwright';
import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import { base } from '../../playwright.config';

const concordance = `${base}/concordance/`;

async function expectNoAxeViolations(page: import('@playwright/test').Page) {
	const { violations } = await new AxeBuilder({ page }).analyze();
	expect(violations).toEqual([]);
}

test('a filtered concordance URL restores its analytical state under the base path', async ({
	page
}) => {
	await page.goto(
		`${concordance}?term=genocide&country=Rwanda&from=2014&to=2014&month=6&sort=right`
	);

	await expect(page.getByRole('heading', { name: 'Concordance', level: 1 })).toBeVisible();
	await expect(page.getByRole('combobox', { name: 'Speaker', exact: true })).toHaveValue('Rwanda');
	await expect(page.getByRole('combobox', { name: 'Month', exact: true })).toHaveValue('6');
	await expect(page.getByRole('button', { name: 'Right' })).toHaveAttribute('aria-pressed', 'true');
	await expect(page.locator('.status')).toContainText('2 of 2 lines');
	await expect(page).toHaveURL(/\/genocide-at-the-security-council\/concordance\//);
	await expectNoAxeViolations(page);
});

test('the filtered CSV records filters, provenance, and only matching rows', async ({ page }) => {
	await page.goto(`${concordance}?q=warned`);
	await expect(page.locator('.status')).toContainText('1 of 2 lines');

	const pending = page.waitForEvent('download');
	await page.getByRole('button', { name: 'Export 1 to CSV' }).click();
	const download = await pending;
	const path = await download.path();
	expect(path).not.toBeNull();
	const csv = await readFile(path!, 'utf8');

	expect(download.suggestedFilename()).toBe('unsc-genocide-concordance-filtered.csv');
	expect(csv).toContain('# artifact: kwic/genocide.json');
	expect(csv).toContain('# pipeline commit: fixture');
	expect(csv).toContain('# on screen: search: warned; sorted by: date');
	expect(csv).toContain('UNSC_2014_SPV.7000_spch0001#1');
	expect(csv).not.toContain('UNSC_2014_SPV.7000_spch0001#2');
});

test('an exported figure embeds its reading and provenance in the image', async ({ page }) => {
	await page.goto(`${base}/`);
	const figure = page.locator('figure.figure').filter({
		has: page.getByRole('heading', { name: /Occurrences and share of speeches/, level: 2 })
	});
	await expect(figure.locator('.chart svg')).toBeVisible({ timeout: 15_000 });

	const pending = page.waitForEvent('download');
	await figure.getByRole('button', { name: 'SVG', exact: true }).click();
	const download = await pending;
	const path = await download.path();
	expect(path).not.toBeNull();
	const svg = await readFile(path!, 'utf8');

	expect(download.suggestedFilename()).toBe('unsc-occurrences-and-share.svg');
	expect(svg).toContain('Occurrences and share of speeches');
	expect(svg).toContain('drawn: genocide — occurrences and share of speeches');
	expect(svg).toContain('artifact: series/annual.json');
	expect(svg).toContain('generated by: 04_series.py on 2026-08-24T00:00:00Z');
	expect(svg).toContain('pipeline commit: fixture');
});

test('a concordance hit opens, copies, and traverses exact occurrences', async ({
	context,
	page
}) => {
	await context.grantPermissions(['clipboard-read', 'clipboard-write']);
	await page.goto(concordance);
	await page.locator('.line').first().click();
	const evidence = page.getByRole('link', { name: 'Read the whole speech' });
	await expect(evidence).toHaveAttribute(
		'href',
		`${base}/reader/UNSC_2014_SPV.7000?term=genocide&speech=UNSC_2014_SPV.7000_spch0001&occurrence=UNSC_2014_SPV.7000_spch0001%231`
	);
	await evidence.click();

	await expect(
		page.getByRole('heading', { name: 'Protection of civilians', level: 1 })
	).toBeVisible();
	await expect(page.locator('li.target')).toHaveAttribute('id', 'UNSC_2014_SPV.7000_spch0001');
	await expect(page.locator('li.target mark')).toHaveCount(2);
	await expect(page.locator('mark.occurrence')).toHaveCount(1);
	await expect(page.locator('mark.occurrence')).toHaveText('genocide');
	await expect(page.locator('mark.occurrence')).toHaveAttribute(
		'data-occurrence',
		'UNSC_2014_SPV.7000_spch0001#1'
	);
	await expect(page.locator('mark.occurrence')).toBeInViewport();
	await page.getByRole('button', { name: 'Copy occurrence link' }).click();
	await expect(page.getByRole('button', { name: 'Occurrence link copied' })).toBeVisible();
	expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(page.url());
	await page.getByRole('button', { name: 'Copy quotation + citation' }).click();
	await expect(page.getByRole('button', { name: 'Quotation copied' })).toBeVisible();
	const quotation = await page.evaluate(() => navigator.clipboard.readText());
	expect(quotation).toContain('“We warned that genocide could occur.”');
	expect(quotation).toContain('Rwanda, UN Security Council, S/PV.7000 (2014-06-11).');
	expect(quotation).toContain('occurrence UNSC_2014_SPV.7000_spch0001#1.');
	expect(quotation).toContain(page.url());
	await expect(page.getByText('1 of 2', { exact: true })).toBeVisible();
	await page.getByRole('link', { name: 'Next occurrence' }).click();
	await expect(page.locator('mark.occurrence')).toHaveAttribute(
		'data-occurrence',
		'UNSC_2014_SPV.7000_spch0001#2'
	);
	await expect(page.getByText('2 of 2', { exact: true })).toBeVisible();
	await expect(page.getByRole('link', { name: 'Previous occurrence' })).toBeVisible();
	await expectNoAxeViolations(page);
});

test('data failure has an intelligible retry path', async ({ page }) => {
	await page.goto(`${concordance}?term=temporarily-unavailable`);
	await expect(page.locator('.status .error')).toContainText(
		'No data file at kwic/temporarily-unavailable.json (404)'
	);

	const body = await readFile(
		new URL('../fixtures/data/kwic/genocide.json', import.meta.url),
		'utf8'
	);
	await page.route('**/data/kwic/temporarily-unavailable.json', (route) =>
		route.fulfill({ status: 200, contentType: 'application/json', body })
	);
	await page.getByRole('button', { name: 'Try again' }).click();
	await expect(page.locator('.status')).toContainText('2 of 2 lines');
});

test('essential concordance controls remain visible at narrow and wide widths', async ({
	page
}) => {
	for (const viewport of [
		{ width: 390, height: 844 },
		{ width: 1440, height: 900 }
	]) {
		await page.setViewportSize(viewport);
		await page.goto(concordance);
		await expect(page.getByRole('combobox', { name: 'Term', exact: true })).toBeVisible();
		await expect(page.getByRole('searchbox', { name: 'Search', exact: true })).toBeVisible();
		await expect(page.locator('.line').first()).toBeVisible();
	}
});

test('keyboard users retain the actor table and evidence link when the map fails', async ({
	page
}) => {
	await page.route('https://basemaps.cartocdn.com/**', (route) => route.abort('failed'));
	await page.goto(`${base}/actors/?order=token_rate&view=choropleth`);

	await expect(page.getByRole('heading', { name: 'Who said it', level: 1 })).toBeVisible();
	await expect(page.getByRole('combobox', { name: 'Ranked by' })).toHaveValue('token_rate');
	await expect(page.getByRole('button', { name: 'Filled' })).toHaveAttribute(
		'aria-pressed',
		'true'
	);
	await expect(page).toHaveURL(/\/actors\/?\?order=token_rate&view=choropleth$/);
	await expect(page.getByRole('status')).toContainText(
		'Every speaker it would show is in the table',
		{ timeout: 8_000 }
	);
	const table = page.locator('section.table-wrap');
	const rwanda = table.getByRole('button', { name: 'Rwanda' });
	await rwanda.focus();
	await page.keyboard.press('Enter');

	const picked = page.locator('aside.picked');
	await expect(picked.getByRole('heading', { name: 'Rwanda' })).toBeVisible();
	await expect(picked.getByRole('link', { name: 'Read the occurrences' })).toHaveAttribute(
		'href',
		`${base}/concordance?term=genocide&country=Rwanda&from=1992&to=2023`
	);
	await expectNoAxeViolations(page);
});
