"""Build web/static/geo/countries.json — the polygons the choropleth fills.

    python tools/build_boundaries.py

The output is **committed**, unlike everything under `web/static/data/`. That is
deliberate. The payload the pipeline writes is derived from the Dataverse pin,
so it belongs to the corpus hash and is rebuilt whenever the corpus is; a world
boundary file is derived from Natural Earth and from `config/entities.csv`, and
making it a pipeline artefact would tie a map of the world to a version of the
speech record it has nothing to do with. It is an asset, like `og.png`, and it
is generated by a script rather than by hand so that its provenance is a command
somebody else can run.

Only this tool touches the network; the pipeline never does.

**What it keys on.** `config/entities.csv` is the crosswalk, so its `iso3`
column is the join key and the only one. A Natural Earth feature whose code the
corpus never uses is dropped: the file is the corpus's map, not a world atlas,
and shipping 30 KB of polygons for states that never spoke would invite a
consumer to fill them.

**What it cannot do.** A fill is territory, and territory is a claim in a way
that a centroid is not. Three decisions are therefore written down rather than
inherited from whatever Natural Earth happened to ship:

- *Kosovo* carries no ISO code in Natural Earth (`ISO_A3` is `-99`). The corpus
  uses `XKX`, which is the code the UN Statistics Division uses, so the feature
  is remapped to it and Kosovo is filled separately from Serbia.
- *Somaliland* and *Northern Cyprus* are separate features in Natural Earth and
  are folded into Somalia and Cyprus. Neither is a speaker in this corpus, and
  leaving them out would put an unexplained hole inside a country the map does
  fill — a hole a reader would read as missing data.
- *Western Sahara* is **not** folded into Morocco and stays unfilled. The UN
  treats it as a non-self-governing territory; folding it in would state the
  opposite in the one channel this figure cannot caveat.

Source: Natural Earth 1:110m Admin 0 - Countries, via nvkelso/natural-earth-vector
at the tag pinned below. Natural Earth is public domain. Coordinates are rounded
to two decimals — about a kilometre, well under one pixel at any zoom this map
offers — which is most of what makes the file small enough to commit.
"""

from __future__ import annotations

import hashlib
import json
import sys
import urllib.request
from pathlib import Path
from typing import Any

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))
from lib import console
from lib.entities import load_entities
from lib.paths import ENTITIES, INTERIM, ROOT, atomic_write_text, ensure_dirs, rel

#: Pinned to a release tag, never to `master`: the point of a committed asset is
#: that re-running this tool reproduces it.
NE_TAG = "v5.1.2"
NE_URL = (
    f"https://raw.githubusercontent.com/nvkelso/natural-earth-vector/{NE_TAG}"
    "/geojson/ne_110m_admin_0_countries.geojson"
)

OUT = ROOT / "web" / "static" / "geo" / "countries.json"
CACHE = INTERIM / "reference" / f"ne_110m_admin_0_countries_{NE_TAG}.geojson"

#: Natural Earth's code for a feature -> the code `config/entities.csv` uses.
#: Every entry is a judgement, and each one is argued in the module docstring.
REMAP: dict[str, str] = {
    "KOS": "XKX",  # Kosovo — no ISO code in Natural Earth
    "SOL": "SOM",  # Somaliland — folded in, not a speaker here
    "CYN": "CYP",  # Northern Cyprus — folded in, not a speaker here
}

#: Decimal places kept. Two is ~1.1 km at the equator; this map's deepest zoom
#: puts several kilometres in a pixel.
PRECISION = 2


def download() -> dict[str, Any]:
    """Natural Earth at the pinned tag, cached under data/interim/reference/."""
    if CACHE.exists():
        console.info(f"cached {rel(CACHE)}")
    else:
        console.info(f"downloading {NE_URL}")
        CACHE.parent.mkdir(parents=True, exist_ok=True)
        with urllib.request.urlopen(NE_URL, timeout=120) as response:
            CACHE.write_bytes(response.read())
    payload = CACHE.read_bytes()
    console.info(f"sha256 {hashlib.sha256(payload).hexdigest()[:16]}… ({len(payload) / 1e6:.1f} MB)")
    return json.loads(payload)


def code_of(properties: dict[str, Any]) -> str | None:
    """The ISO 3166-1 alpha-3 code for one Natural Earth feature.

    `ISO_A3_EH` rather than `ISO_A3`: the latter is `-99` for France and Norway,
    among others, because Natural Earth records the code on the sovereign rather
    than on the metropolitan feature. `ADM0_A3` is the fallback, and it is
    Natural Earth's own invention for the handful of features ISO does not code
    at all — which is why `REMAP` exists.
    """
    iso = str(properties.get("ISO_A3_EH") or "")
    if iso and iso != "-99":
        return REMAP.get(iso, iso)
    admin = str(properties.get("ADM0_A3") or "")
    if not admin or admin == "-99":
        return None
    return REMAP.get(admin, admin)


def round_ring(ring: list[list[float]]) -> list[list[float]] | None:
    """One ring, rounded, with the points rounding made identical removed.

    A ring that keeps fewer than four points after that has collapsed to a line
    and is dropped: it would render as nothing and might not render at all.
    """
    out: list[list[float]] = []
    for x, y in ring:
        point = [round(float(x), PRECISION), round(float(y), PRECISION)]
        if not out or point != out[-1]:
            out.append(point)
    if len(out) < 4:
        return None
    if out[0] != out[-1]:
        out.append(out[0])
    return out if len(out) >= 4 else None


def round_polygon(polygon: list[list[list[float]]]) -> list[list[list[float]]] | None:
    """A polygon is its outer ring and its holes. No outer ring, no polygon."""
    rings = [rounded for ring in polygon if (rounded := round_ring(ring)) is not None]
    return rings or None


def parts_of(geometry: dict[str, Any]) -> list[list[list[list[float]]]]:
    """Every polygon in a geometry, as a list, whatever the geometry's type."""
    if geometry["type"] == "Polygon":
        return [geometry["coordinates"]]
    if geometry["type"] == "MultiPolygon":
        return list(geometry["coordinates"])
    return []


def main() -> None:
    ensure_dirs()
    console.step("Reading the crosswalk")
    entities = load_entities()
    wanted = {str(code) for code in entities["iso3"].dropna().unique()}
    console.info(f"{len(wanted)} ISO3 codes in {rel(ENTITIES)}")

    console.step("Reading Natural Earth")
    world = download()
    console.info(f"{len(world['features'])} features at 1:110m")

    console.step("Joining on ISO3")
    # Grouped rather than mapped one-to-one: a fold (Somaliland into Somalia)
    # means two features share a code, and both sets of rings have to survive.
    grouped: dict[str, list[list[list[list[float]]]]] = {}
    names: dict[str, str] = {}
    unmatched: list[str] = []
    for feature in world["features"]:
        properties = feature["properties"]
        code = code_of(properties)
        if code is None:
            unmatched.append(str(properties.get("NAME") or "?"))
            continue
        if code not in wanted:
            continue
        polygons = [p for part in parts_of(feature["geometry"]) if (p := round_polygon(part))]
        if not polygons:
            console.warn(f"{code} has no ring left after rounding — dropped")
            continue
        grouped.setdefault(code, []).extend(polygons)
        # A fold keeps the *sovereign's* name, not whichever feature the file
        # happened to list first: Northern Cyprus precedes Cyprus in Natural
        # Earth's order, and taking the first would have labelled CYP with the
        # name of the part folded into it. The name is for reading the file by
        # hand; nothing in the interface reads it.
        folded = code not in {properties.get("ISO_A3_EH"), properties.get("ADM0_A3")}
        if not folded or code not in names:
            names[code] = str(properties.get("NAME") or code)

    features = [
        {
            "type": "Feature",
            "id": code,
            "properties": {"iso3": code, "name": names[code]},
            "geometry": (
                {"type": "Polygon", "coordinates": polygons[0]}
                if len(polygons) == 1
                else {"type": "MultiPolygon", "coordinates": polygons}
            ),
        }
        for code, polygons in sorted(grouped.items())
    ]

    missing = sorted(wanted - set(grouped))
    console.info(f"{len(features)} of {len(wanted)} corpus codes have a polygon")
    if unmatched:
        console.info(f"{len(unmatched)} Natural Earth features carry no usable code: {', '.join(sorted(unmatched))}")
    if missing:
        # Not a failure. Natural Earth's 110m sheet omits states below a size
        # threshold, and the interface draws those speakers as a square at their
        # centroid rather than dropping them — see `web/src/lib/choropleth.ts`.
        console.warn(f"{len(missing)} corpus codes have no polygon at this resolution:")
        console.info(", ".join(missing))

    collection = {
        "type": "FeatureCollection",
        # Foreign members. GeoJSON permits them, MapLibre ignores them, and a
        # file that says where it came from cannot be mistaken for one somebody
        # dropped in by hand.
        "source": {
            "name": "Natural Earth 1:110m Admin 0 - Countries",
            "url": NE_URL,
            "tag": NE_TAG,
            "licence": "public domain",
            "built_by": "tools/build_boundaries.py",
            "precision": PRECISION,
            "keyed_on": "ISO 3166-1 alpha-3, as in config/entities.csv",
            "without_polygon": missing,
        },
        "features": features,
    }

    OUT.parent.mkdir(parents=True, exist_ok=True)
    atomic_write_text(OUT, json.dumps(collection, separators=(",", ":")))
    console.step("Wrote the boundaries")
    console.table(
        [
            ("file", rel(OUT)),
            ("features", len(features)),
            ("size", f"{OUT.stat().st_size / 1024:.0f} KB"),
            ("without a polygon", len(missing)),
        ]
    )


if __name__ == "__main__":
    main()
