"""Write scripts/deps.mk — each pipeline step's real `lib` prerequisites.

    python tools/lib_deps.py          # rewrite scripts/deps.mk
    python tools/lib_deps.py --check  # exit non-zero if it is stale

The Makefile used to make every step depend on every module under
`scripts/lib/`, so editing the usage aggregation rebuilt the corpus from step
01. This reads each script's imports — `from lib import x`, `from lib.x import
y` — and follows `lib`'s own relative imports to a fixed point, so a step
depends on exactly the modules it can execute. The result is committed, and
`tests/test_build_graph.py` fails when it no longer matches the source.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
LIB = SCRIPTS / "lib"
OUTPUT = SCRIPTS / "deps.mk"

HEADER = """\
# Generated by tools/lib_deps.py from the imports; do not edit by hand.
# Each step's `lib` modules, followed transitively. The Makefile names a step's
# variable where it used to name every module, so a module edit rebuilds only
# the steps that can execute it.
"""


def _lib_imports(path: Path, *, inside_lib: bool) -> set[str]:
    """Module names under `lib` that one file imports."""
    found: set[str] = set()
    for node in ast.walk(ast.parse(path.read_text(encoding="utf-8"))):
        if isinstance(node, ast.ImportFrom):
            if inside_lib and node.level == 1:
                if node.module:
                    found.add(node.module.split(".")[0])
                else:
                    found.update(alias.name for alias in node.names)
            elif node.level == 0 and node.module == "lib":
                found.update(alias.name for alias in node.names)
            elif node.level == 0 and node.module and node.module.startswith("lib."):
                found.add(node.module.split(".")[1])
        elif isinstance(node, ast.Import):
            for alias in node.names:
                if alias.name.startswith("lib."):
                    found.add(alias.name.split(".")[1])
    return {name for name in found if (LIB / f"{name}.py").is_file()}


def closure(script: Path) -> list[str]:
    """Every `lib` module a script can execute, as repository-relative paths."""
    pending = list(_lib_imports(script, inside_lib=False))
    seen: set[str] = set()
    while pending:
        name = pending.pop()
        if name in seen:
            continue
        seen.add(name)
        pending.extend(_lib_imports(LIB / f"{name}.py", inside_lib=True) - seen)
    return sorted(f"scripts/lib/{name}.py" for name in seen)


def variable(script: Path) -> str:
    return "LIB_" + script.stem.upper().replace("-", "_")


def render() -> str:
    lines = [HEADER]
    for script in sorted(SCRIPTS.glob("*.py")):
        modules = closure(script)
        lines.append(f"{variable(script)} := scripts/lib/__init__.py " + " ".join(modules))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify only")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python tools/lib_deps.py")
            sys.exit(1)
        print(f"{OUTPUT.relative_to(ROOT)} matches the imports")
        return
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
