"""Write scripts/deps.mk — each pipeline step's real `lib` prerequisites.

    python tools/lib_deps.py          # rewrite scripts/deps.mk
    python tools/lib_deps.py --check  # exit non-zero if it is stale

A step depends on exactly the modules it can execute, so editing the usage
aggregation does not rebuild the corpus from step 01. The closure is
`lib.artifacts.lib_closure`, the same one every step's manifest records its
code from, so the graph make rebuilds by and the code a manifest names cannot
disagree. The result is committed, and `tests/test_build_graph.py` fails when it
no longer matches the source.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SCRIPTS = ROOT / "scripts"
OUTPUT = SCRIPTS / "deps.mk"

sys.path.insert(0, str(SCRIPTS))
from lib.artifacts import lib_closure

HEADER = """\
# Generated by tools/lib_deps.py from the imports; do not edit by hand.
# Each step's `lib` modules, followed transitively. The Makefile names a step's
# variable where it used to name every module, so a module edit rebuilds only
# the steps that can execute it.
"""


def closure(script: Path) -> list[str]:
    """Every `lib` module a script can execute, as repository-relative paths."""
    return [path.relative_to(ROOT).as_posix() for path in lib_closure(script)]


def variable(script: Path) -> str:
    return "LIB_" + script.stem.upper().replace("-", "_")


def render() -> str:
    lines = [HEADER]
    for script in sorted(SCRIPTS.glob("*.py")):
        modules = closure(script)
        lines.append(f"{variable(script)} := scripts/lib/__init__.py " + " ".join(modules))
    return "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="verify only")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != text:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run python tools/lib_deps.py")
            sys.exit(1)
        print(f"{OUTPUT.relative_to(ROOT)} matches the imports")
        return
    OUTPUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
